### PR TITLE
fix len-as-condition linting issues

### PR DESCRIPTION
**Pull request by jackneary**
replaced "len(list) !=0" to just "list"

### CODE REVIEW

**Comment by jackneary** [comment]
@justinnhli @crzeller11

**Comment by justinnhli** [comment]
Please rebase on master

**Comment by justinnhli** [comment]
@NickBethune I assume you meant to add the synonym dictionary stuff in a different branch, not to this pull request.

**Comment by jackneary** [comment]
@justinnhli yes he did, but let me know if more needs to be done in this pull request please

**Comment by justinnhli** [comment]
@jackneary I would revert to before that commit and rebase on the current master first. I'll look at it again then.

**Comment by jackneary** [comment]
@justinnhli I'm sorry if i didn't do this correctly, but I reverted nick's most recent commit on my branch and I believe it is rebased to the master

**Comment by justinnhli** [comment]
@jackneary Don't think that worked. Make sure you've pushed as well? GitKraken should warn that you are Force Pushing

**Comment by jackneary** [comment]
@justinnhli ahhh SHOOT you're right, how does it look now?

**Comment by justinnhli** [comment]
Don't think so.

1. Hard revert back to 6f14fa2b864a859eba695a6df36832d79142b42e ("add ignore statements for lint")
2. Right click on master and "Rebase - onto master"

**Comment by justinnhli** [comment]
You can also check the whether it worked on the network graph: https://github.com/oxy-compsci/ReChord/network

Your branch should be only coming out of Master

**Comment by jackneary** [comment]
@justinnhli that is great information to have in the future, thank you. I think it's all worked out now

**Pull request closed without merging**
