### PR TITLE
Working and updated frontend

### PR DESCRIPTION
**Pull request by yinbogao**
1. New Front end with <textarea> input instead of <input>
2. Use Accordion for user uploaded database.
snip20180423_5

3. New Result page, used <table>. 
snip20180423_3

4. Term search working properly.
5. Fixed tempdir upload.

Next step: Needs test cases on front-end and return error page. @justinnhli @crzeller11

### CODE REVIEW

**Comment by justinnhli** [comment]
No coding issues, but re: the front end:

1. The first column should be clearer that you mean *number* of matches
2. The last column should not be in python syntax, but just the measure numbers separated by commas.

Fix, post a screenshot, and I'll merge.

**Comment by Lijia-Li** [comment]
screen shot 2018-04-23 at 3 03 50 pm
@justinnhli

**Comment by justinnhli** [comment]
What happened to the author name?

**Comment by yinbogao** [comment]
@justinnhli It's not our fault, we checked specifically for that error last weekend. In the xml file that was exactly how it was coded by the creator.

**Comment by justinnhli** [comment]
But it's rendered properly in your first screenshot...?

**Comment by Lijia-Li** [comment]
That is because the file we are using is different. 

Chopin.xml
screen shot 2018-04-23 at 3 28 40 pm

Chopin_Etude_op.10_no.9.mei
screen shot 2018-04-23 at 3 28 46 pm

And they all have the same title.

**Comment by yinbogao** [comment]
@justinnhli hmmmm let me look into it. Maybe our database are different. There were duplicating files in the database and one of them has the weird name.

**Comment by justinnhli** [comment]
@yinbogao @Lijia-Li duplicated documents make sense. If you don't have other comments, I will merge this within the hour.

**Pull request merged**
